server:
  port: 9181
#  servlet:
#    context-path: /

logging:
  file:
    name: logs/webappmvc.log
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

spring:
  profiles:
    active: default
  application:
    name: webapp-mvc
  jpa-ordering:
    properties:
      hibernate:
        hbm2ddl.auto: update
        format_sql: true
        use_sql_comments: true
  jpa-management:
    properties:
      hibernate:
        hbm2ddl.auto: update
        format_sql: true
        use_sql_comments: true
  datasource:
    ordering:
      jdbc-url: jdbc:mysql://localhost:3306/ordering_db
      username: root
      password: Password123
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        pool-name: HikariOrderingPool
        max-lifetime: 1800000

    management:
      jdbc-url: jdbc:postgresql://localhost:5432/management_db
      username: postgres
      password: Password123
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        pool-name: HikariManagementPool
        max-lifetime: 1800000

  jpa:
    show-sql: true
    open-in-view: false
